In [3]:
%pip install numpy



Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
a= np.zeros(10)
print(a)
a

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
import numpy as np
a= np.zeros(10)
print(a)
type(a[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


numpy.float64

In [13]:
b=np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
np.ones
np.empty

<function numpy.empty>

In [19]:
z=np.zeros(5)
print(z.shape)

(5,)


In [29]:
z.shape = (5, 1)
z
# np.arrange(10)  # This is a typo, the correct function is np.arange
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
e=np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
z=np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [35]:
# ARRAY CONCATENATION
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.concatenate((a, b), axis=0)  # Concatenate along rows
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
b=np.array([[7],[8]])
c=np.concatenate((a, b), axis=1)  # Concatenate along columns
c

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [39]:
z=np.random.randint(1,51,size=50)
print(np.sort(z))

[ 1  1  1  1  2  4  4  6  6  7  7  7 11 12 13 14 14 18 20 20 22 22 23 24
 24 25 25 27 28 28 28 29 32 32 34 34 36 36 37 38 38 38 39 39 40 43 43 45
 48 50]


In [42]:
z[0:2]  # Slicing the first 2 elements

array([45,  1], dtype=int32)

In [45]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 1])  # Accessing the element at row 0, column 1

5


In [47]:
a.ndim #dimension of array 


2

In [56]:
np.append(a, [[7, 8, 9]], axis=0)  # Appending a new row
# if we remove axis it will converted to 1d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a=np.insert(a, 1, [7, 8, 9], axis=0)  # Inserting a new row at index 1
a
#the more you run this the more it will insert the same row

array([[1, 2, 3],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [4, 5, 6]])

In [65]:
a=np.delete(a,1)# Deleting the row at index 1
a

array([1, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 4, 5, 6])

In [67]:
a=np.delete(a,1,0)  # Deleting the row at index 1
a

array([1, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 4, 5, 6])

In [74]:
m=np.array([[10,11,12],
            [13,14,15]])
m=np.append(m, [[16,17,18]], axis=0)

In [ ]:
%pip install scikit-image

  Using cached scikit_image-0.25.2-cp313-cp313-win_amd64.whl.metadata (14 kB)
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
  Using cached imageio-2.37.0-py3-none-any.whl.metadata (5.2 kB)
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Using cached scikit_image-0.25.2-cp313-cp313-win_amd64.whl (12.9 MB)
Using cached imageio-2.37.0-py3-none-any.whl (315 kB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
Using cached networkx-3.5-py3-none-any.whl (2.0 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
